version: '3.8'

services:
  savi-app:
    build: .
    container_name: savi-customgpt-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=savi-dev-key-change-in-production
    volumes:
      # Mount source code for development (hot reload)
      - .:/app
      # Mount static files
      - ./static:/app/static
      # Mount templates
      - ./templates:/app/templates
    restart: unless-stopped
    networks:
      - savi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  savi-network:
    driver: bridge
